version: '3.5'

services:

  app:
    user: '1000'
    build:
      context: ./step
      dockerfile: Dockerfile
      target: development
    command: [ "npm run dev" ]
    ports:
      - $APP_PORT:4200
      - $APP_PREVIEW_PORT:4173
    volumes:
      - ../src/step:/srv/app
