version: '3.5'

services:

  app:
    user: $APP_UID
    build:
      context: ./step
      dockerfile: Dockerfile
      target: development
    command: [ "npm run dev" ]
    ports:
      - $APP_PORT:4200
    volumes:
      - ../src/step:/srv/app
